[book]
title = "Avalia Ai - Projeto"
authors = ["Lucas Edson",  "Robson Pereira", "Gabriel Henrique", "Raphael Moura", "Ícaro Wanderley", "Rosimar Cavalcante", "Igor Jose", "Erick Reis da Silva"]
language = "pt-br"
src = "src"
